#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AMUN_TMPDIR=$(mktemp -d)
PLATFORM="${1:-debian}"

trap 'rm -rf "$AMUN_TMPDIR"' EXIT SIGINT SIGTERM

git clone https://github.com/GonzaloAlvarez/amun.git "$AMUN_TMPDIR/amun"
cp -r "$SCRIPT_DIR" "$AMUN_TMPDIR/amun-iossync"

"$AMUN_TMPDIR/amun/test" "$PLATFORM" -p iossync
